// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using ML_Sentiment;
using System.IO;

#region Builder
// Configure app
var builder = WebApplication.CreateBuilder(args);

#region Machine Learning Datasets
// ENG
string modelPath = Path.GetFullPath("../../Datasets/MLSentiment_Datasets/MLSentimentModel.zip");
builder.Services.AddPredictionEnginePool<MLSentimentModel.ModelInput, MLSentimentModel.ModelOutput>()
    .FromFile("MLSentimentModel", modelPath);

// ESP
string modelPathESP = Path.GetFullPath("../../Datasets/MLSentiment_Datasets/MLSentimentModelESP.zip");
builder.Services.AddPredictionEnginePool<MLSentimentModelESP.ModelInputESP, MLSentimentModelESP.ModelOutputESP>()
    .FromFile("MLSentimentModelESP", modelPathESP);
#endregion

builder.Services.AddEndpointsApiExplorer();

#region Swagger
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Sentimentator", Description = "Sentimentator: Machine Learning API to predict the sentiment of a given text.", Version = "v1" });
});
#endregion
builder.Services.AddControllers();
#endregion

#region App
var app = builder.Build();
#region Swagger
app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "Sentimentator");
});
#endregion
app.UseHttpsRedirection();
app.MapControllers();
app.Run();
#endregion