// This file was auto-generated by ML.NET Model Builder.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace MLSentimentModelESP_WebApi
{
    public partial class MLSentimentModelESP
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"ns", @"ns", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(@"rev_id", @"rev_id"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"comentario",outputColumnName:@"comentario"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"a�o",outputColumnName:@"a�o"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"conectado",outputColumnName:@"conectado"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"muestra",outputColumnName:@"muestra"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"separar",outputColumnName:@"separar"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"ns",@"rev_id",@"comentario",@"a�o",@"conectado",@"muestra",@"separar"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Etiqueta",inputColumnName:@"Etiqueta"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(new LbfgsMaximumEntropyMulticlassTrainer.Options(){L1Regularization=0.03125F,L2Regularization=0.0601619F,LabelColumnName=@"Etiqueta",FeatureColumnName=@"Features"}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
